---
### Site metadata ###

site_name: choreographer
repo_name: github


### Build settings ###

docs_dir: 'docs/'
nav:
  - Readme: >-
      {
        "dest": "README.md",
        "src": "../README.md",
        "replace": {"src='docs/": "src='"}
      }
  - User API: >-
        {
          "api": "choreographer",
          "test": ["exports", "_prefix_local"],
          "tree": "none"
        }
  - Developer API:
      - >-
        {
          "api": "choreographer",
          "test": ["exports", "_prefix_local"],
          "tree": "packages"
        }
  # CLI tools?

theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - quimeta
  - quicopy
  - quiapi
