[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {namespaces = false}

[project]
name = "devtools"
description = "Devtools protocol"
requires-python = ">=3.9"
version = "0.0.1"

[project.optional-dependencies]
dev = [
  "pytest",
  ]

[project.scripts]
devtools-doctor = "devtools.browser:diagnose"

[tool.ruff.lint]
ignore = ["E701"]
