[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {namespaces = false}

[project]
name = "choreographer"
description = "Devtools Protocol implementation for chrome"
requires-python = ">=3.9"
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-asyncio",
  "pytest-xdist",
  "async-timeout"
  ]

[project.scripts]
dtdoctor = "choreographer.browser:diagnose"

[tool.ruff.lint]
ignore = ["E701"]

[tool.setuptools-git-versioning]
enabled = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

