[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {namespaces = false}

[project]
name = "devtools"
description = "Devtools protocol"
requires-python = ">=3.9"
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-asyncio",
  "pytest-xdist",
  "pytest-timeout"
  ]

[project.scripts]
dtdoctor = "devtools.browser:diagnose"

[tool.ruff.lint]
ignore = ["E701"]

[tool.setuptools-git-versioning]
enabled = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
# addopts = "-v -n auto --timeout=4"
## Verbosity:
# -vv -rA
## Parallelism:
# -n auto
## Timeout:
# --timeout=4
