# .github/workflows/publish_testpypi.yml
---
name: test-n-build
on: pull_request
  #  push:
  #    tags:
  #      - v*
jobs:
  super-test:
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]
        pyvers: [3.09] #, 3.10, 3.11, 3.12, 3.13]
    name: Build and Test
    runs-on: ${{ matrix.os }}
    environment:
      name: pypi
      url: https://pypi.org/p/pozo
    # IMPORTANT: this permission is mandatory for trusted publishing
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: uv python install ${{ matrix.pyvers }}
      - run: uv build
      - run: uv venv
      - run: ls && export && uv pip install dist/choreographer*.whl

    # different versions of chrome

  #    REMEMBER TO GO BACK ONE COMMIT ON OTHER BRANCH
  #- name: Publish package distributions to PyPI
  #  uses: pypa/gh-action-pypi-publish@release/v1
