name: test-wf

on: pull_request
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
      - name: Install Dependencies
        run:  sudo apt-get update && sudo apt-get install chromium-browser
      - uses: ./.github/workflows/common-test-fragment.yml
        with: ubuntu-latest
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Dependencies
        run:  choco install googlechrome -y --ignore-checksums
      - name: Install devtools
        run:  pip install .[dev]
      - name: DTDoctor
        run:  dtdoctor
        timeout-minutes: 3
      - name: Test Process Control
        run:  pytest -vv -rA tests/test_process.py
        timeout-minutes: 1
      - name: Test the Rest
        run:  pytest -vv -rA --ignore=tests/test_process.py
        timeout-minutes: 1
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Dependencies
        run:  brew install google-chrome
      - name: Install devtools
        run:  pip install .[dev]
      - name: DTDoctor
        run:  dtdoctor
        timeout-minutes: 3
      - name: Test Process Control
        run:  pytest -vv -rA tests/test_process.py
        timeout-minutes: 1
      - name: Test the Rest
        run:  pytest -vv -rA --ignore=tests/test_process.py
        timeout-minutes: 1
