---
name: test-wf
on: pull_request
jobs:
  test-all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: >
          sudo apt-get update &&
          sudo apt-get install xvfb &&
          alias uv='xvfb-run uv'
        timeout-minutes: 1

      - name: Install choreographer
        run:  uv sync --all-extras
      - name: Install google-chrome-for-testing
        run: uv run choreo_get_browser
      - name: Diagnose
        run:  uv run choreo_diagnose --no-run
        timeout-minutes: 1

      - name: Test
        if: ${{ ! runner.debug }}
        run: uv run poe test
        timeout-minutes: 4
      - name: Test (Debug)
        if: runner.debug
        run: uv run poe debug-test
        timeout-minutes: 10
