name: test-wf

on: pull_request
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1 # Would be nice to bump this? Regressions.
      - name: Install Dependencies
        run:  sudo apt-get update && sudo apt-get install chromium-browser
        #- uses: ./.github/actions/ # it would be nice but it doesn't support timeout-minutes
      - name: Install devtools
        run:  pip install .[dev]
      - name: DTDoctor
        run:  dtdoctor
        timeout-minutes: 3
      - name: Test Process Control
        run:  pytest -vv -rA -k no_context tests/test_process.py # x-dist problems on linux GHA?
        timeout-minutes: 1
      - name: Test the Rest
        run:  pytest -vv -rfE --ignore=tests/test_process.py
        timeout-minutes: 1
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Dependencies
        run:  choco install googlechrome -y --ignore-checksums
      #- uses: ./.github/actions/
      - name: Install devtools
        run:  pip install .[dev]
      - name: DTDoctor
        run:  dtdoctor
        timeout-minutes: 3
      - name: Test Process Control
        run:  pytest -vv -rfE -n auto tests/test_process.py
        timeout-minutes: 1
      - name: Test the Rest
        run:  pytest -vv -rfE --ignore=tests/test_process.py
        timeout-minutes: 1
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Dependencies
        run:  brew install google-chrome
      #- uses: ./.github/actions/
      - name: Install devtools
        run:  pip install .[dev]
      - name: DTDoctor
        run:  dtdoctor
        timeout-minutes: 3
      - name: Test Process Control
        run:  pytest -vv -rfE -n auto tests/test_process.py
        timeout-minutes: 1
      - name: Test the Rest
        run:  pytest -vv -rfE --ignore=tests/test_process.py
        timeout-minutes: 1
